name: snakehead
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::python>3.7
  - bioconda::nextflow
  - conda-forge::biopython
  - conda-forge::pydot
  - conda-forge::numpy
  - conda-forge::graph-tool
